[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SlicerDESI"
authors = [{name = "Jade Warren", email = "19jw90@queensu.ca"}]
dynamic = ["version", "description"]
